openapi: 3.0.3
info:
  title: SER-CQ API
  description: API documentation for the SER-CQ service.
  version: 1.0.0
servers:
  - url: https://api.example.com
    description: Production server
  - url: https://staging-api.example.com
    description: Staging server
paths:
  /piattaforma-notifiche:
    post:
      summary: Invia una notifica digitale
      description: Endpoint per inviare notifiche digitali a valore legale.
      security:
        - PDND_JWT: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DigitalNotificationRequest'
            
      responses:
        '200':
          description: Richiesta elaborata con successo.
        '400':
          description: Richiesta non valida.
        '500':
          description: Errore interno del server.

components:
  securitySchemes:
    PDND_JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >-
        Autenticazione tramite token JWT validato da PDND. Il token deve essere incluso
        nell'header `Authorization` come `Bearer <token>`.

  schemas:

    DigitalNotificationRequest:
      title: schema per notifiche a valore legale, con allegati
      allOf:
        - type: object
          required:
            - requestId
            - receiverSercqAddress
            - subjectText
            - messageContentType
            - attachment
          properties:
            requestId:
              type: string
              description: >-
                Identificativo della richiesta.
              example: "12345"
            receiverSercqAddress:
              type: string  
              description: >-
                Indirizzo del destinatario all'interno del dominio del SERCQ.
              example: "RSSMRA85M01H501Z"
            subjectText:
              type: string
              description: >-
                Oggetto  del corpo della comunicazione digitale.
              example: "Oggetto della notifica"
            messageContentType:
              type: string
              enum:
                - 'text/plain'
                - 'text/html'
              description: >-
                Formato: HTML o PLAIN.
              example: "Caro utente, questo è un messaggio di prova da parte di XXXX "
            attachment:
              type: object
              description: >-
                Documento di Allegato Avvenuta Ricezione (AAR) della notifica.
              properties:
                filename:
                  type: string
                  description: Name of the file.
                  example: "documento.pdf"
                content:
                  type: string
                  format: base64
                  description: Base64 encoded content of the file.
                  example: "VGhpcyBpcyBhIHNhbXBsZSBmaWxlIGNvbnRlbnQ=" # Base64 encoded content
