name: Generate and Commit OpenAPI Docs

on:
  push:
    paths:
      - 'specs/**/*.yml'  # Trigger workflow on changes to any .yml file in the specs folder
  workflow_dispatch:  # Allow manual triggering of the workflow

permissions:
  contents: write  # Allow writing to the repository

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Redoc CLI
        run: npm install -g redoc-cli

      - name: Generate HTML documentation for all specs
        run: |
          for file in specs/**/*.yml; do
            filename=$(basename "$file" .yml)
            redoc-cli bundle "$file" -o "docs/${filename}.html"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/*.html
          git commit -m "Update OpenAPI documentation [skip ci]" || echo "No changes to commit"
          git push
