name: Generate and Commit OpenAPI Docs

on:
  push:
    paths:
      - '**/*.yml'  # Trigger workflow on changes to any .yml file
  workflow_dispatch:  # Allow manual triggering of the workflow

permissions:
  contents: write  # Allow writing to the repository

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Redoc CLI
        run: npm install -g redoc-cli

      - name: Generate HTML documentation
        run: redoc-cli bundle docs/openapi/sercq.yml -o docs/sercq.html

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/sercq.html
          git commit -m "Update OpenAPI documentation [skip ci]" || echo "No changes to commit"
          git push
